#===================> today is introduction class <====================
# python is a interpretative language they read  line by line .. it's is high level language 
# python is design by a signal man ...
# we have basic focus on logic building ...
# python basically we download backend logic and learn how the work in backend / . *(optional)
# OOP simple mean we divide probelm in to small piece simple mean work as a object ... covert probrlm in to simple modulate object form ... example if we want to sum to number then we first simple create a sum funtion the work as object component ...
# focus on problem solving ...
# learn about data type in python (next class task)
# what is data science and data analytic and how this is relative to programming ?
# numpy library why this is used and what it's benifit ... 
# pytouch ki library we use for natural langauage process karvany ga ...
# Django is a frameowrk  , django support reuseabiltly ....(recommanding)(instagram application build on this )
# Flask Is a framework , falsk is basically use for web framework (likndin) build on falsk ...
# google search is completely based on python ...
# NASA Use python for scientific research ....
# youtube also use python video sharing system is havealy based on python ...
# Netflix is also build on python.. also use micro services
# Bigdata ... with the passing of time data is increase day by day ,,
# expolre about linear search and binary search in python ..
#  question prepare for tomorrow ,,, (learn about linear and binary search , anacongda confirmation , overveiw about flask and dnjago , learn some thing new about python , ) 
